/**
 * Security Audit & Mini Project Report Generator for Severa AI
 */

export function generateAuditReportMarkdown(scanMetrics, findings, language, code, aiReviewData) {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const criticals = scanMetrics?.criticalCount || 0;
  const highs = scanMetrics?.highCount || 0;
  const mediums = scanMetrics?.mediumCount || 0;
  const score = scanMetrics?.score || 100;
  const grade = scanMetrics?.grade || 'A+';

  let report = `# MINIPROJECT SECURITY AUDIT REPORT: CONTINUOUS CODE REVIEW & VULNERABILITY DETECTION

**Project Title**: Severa AI Continuous Code Review Engine  
**Audit Date**: ${dateStr}  
**Target Language**: ${language.toUpperCase()}  
**Overall Security Grade**: **${grade}** (Score: **${score}/100**)  

---

## 1. Executive Summary

This Security Audit Report was automatically synthesized by the **Severa AI Continuous Code Review & Vulnerability Detection System**.
The static security analyzer (SAST) and AI contextual reviewer evaluated source code comprising **${scanMetrics?.totalLines || 0} lines** of code.

### Key Metrics Overview
- **Security Score**: ${score} / 100
- **Overall Grade**: ${grade}
- **Total Vulnerabilities Identified**: ${findings.length}
  - **Critical**: ${criticals}
  - **High**: ${highs}
  - **Medium**: ${mediums}
  - **Low / Info**: ${scanMetrics?.lowCount || 0}
- **Cyclomatic Complexity**: ${scanMetrics?.complexity || 1}
- **Maintainability Index**: ${scanMetrics?.maintainability || 100} / 100

---

## 2. Identified Vulnerability Findings

`;

  if (findings.length === 0) {
    report += `> ✅ **No security vulnerabilities were identified in the target codebase.**\n\n`;
  } else {
    findings.forEach((f, idx) => {
      report += `### Finding #${idx + 1}: ${f.title} (${f.severity})

- **Severity**: \`${f.severity}\`
- **Location**: Line ${f.line}
- **CWE Identifier**: [${f.cwe}](${f.cweUrl})
- **OWASP Top 10 Category**: \`${f.owasp}\`
- **Vulnerable Code Snippet**:
  \`\`\`${language}
  ${f.codeSnippet}
  \`\`\`
- **Technical Description**: ${f.description}
- **Security Impact**: ${f.impact}
- **Recommended Remediation**: ${f.remediation}

---
`;
    });
  }

  report += `
## 3. AI Code Reviewer & Auto-Fix Synthesis

**AI Gate Status**: ${aiReviewData?.status || 'N/A'}  
**Remediation Summary**: ${aiReviewData?.remediationDiffSummary || 'Auto-fix patch generated.'}

### AI Remediated Secure Code Patch
\`\`\`${language}
${aiReviewData?.fixedCode || code}
\`\`\`

---

## 4. Academic System Architecture & Methodology

1. **Static Analysis (SAST)**: AST pattern matching and rule engines for detecting OWASP Top 10 flaws (CWE-89 SQLi, CWE-79 XSS, CWE-798 Secrets, CWE-78 RCE).
2. **AI Remediation Engine**: Side-by-side diff generation and contextual refactoring.
3. **CI/CD Quality Gate**: Continuous integration pipeline simulation to enforce security policies on Pull Requests.
4. **Software Composition Analysis (SCA)**: Scanning third-party manifest dependencies for known CVEs.

*Report generated by Severa AI Mini Project Engine.*
`;

  return report;
}
